routes/admin.php
<?php

use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Route;

Route::prefix('dashboard')->name('dashboard.')->group(function () {


    Route::get('/login', 'AdminAuth@login');
    Route::post('/login', 'AdminAuth@doLogin');
    Config::set('auth.defines', 'admin');

    Route::group(['middleware' => 'admin:admin'], function () {

        Route::get('/', 'HomeController@index');

        // admin routes
        Route::resource('admin', 'AdminController');

        // doctor routes
        Route::resource('doctor', 'DoctorController')->except(['create','store']);

        // user routes
        Route::resource('user', 'UserController')->except(['create','store']);

        // reservation routes
        Route::get('reservation', 'ReservationController@allReservation');
        Route::get('reservation/accepted', 'ReservationController@acceptedReservation');
        Route::get('reservation/rejected', 'ReservationController@rejectedReservation');
        Route::get('reservation/report', 'ReservationController@reportReservation');

        Route::post('/logout', 'AdminAuth@logout');

    });


});//end of dashboard routes

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Auth::routes();


Route::namespace('User')->group(function (){

    Route::get('/', 'WelcomeController@index')->name('home');

//    Route::get('/doctor/{doctor}', 'WelcomeController@showDoctor');

    Route::get('/reservation/{id}', 'ReservationController@store')->middleware('auth');


});

app/Models/Doctor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Doctor extends Authenticatable
{
    use Notifiable;


    protected $fillable = [
        'name', 'email', 'password', 'fees', 'location', 'description', 'specialty', 'placement'
    ];

    protected $hidden = [
        'password', 'remember_token', 'email_verified_at', 'created_at', 'updated_at'
    ];


    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getStatusAttribute()
    {
        if ($this->placement === 0) {
            return 'Pending';
        }

        return 'Approved';
    }

    public function scopeApproved($query)
    {
        return $query->where('placement', 1);
    }

    public function reservations()
    {
        return $this->hasMany(Reservation::class);
    }
}

app/Http/Controllers/Admin/DoctorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Doctor;
use App\Notifications\DoctorPlacement;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class DoctorController extends Controller
{
    public function index(Request $request)
    {
        $doctors = Doctor::where(function ($q) use ($request) {

            return $q->when($request->search, function ($query) use ($request) {

                return $query->where('name', 'like', '%' . $request->search . '%')
                    ->orWhere('email', 'like', '%' . $request->search . '%');

            });

        })->latest()->paginate(5);

        return view('admin.doctors.index', compact('doctors'));
    }

    public function edit(Doctor $doctor)
    {
        if ($doctor->placement === 0) {
            $doctor->placement = 1; // Approved doctor
            $doctor->save();

            Mail::to($doctor->email)->send(new \App\Mail\DoctorStatus($doctor->name, $doctor->status));
            $doctor->notify(new DoctorPlacement($doctor->status,$doctor->name));
            toast('Doctor has been Approved successfully','success','top-right')->hideCloseButton();
            return back();
        }

        $doctor->placement = 0;  // pending doctor
        $doctor->save();

        Mail::to($doctor->email)->send(new \App\Mail\DoctorStatus($doctor->name, $doctor->status));
        $doctor->notify(new DoctorPlacement($doctor->status,$doctor->name));
        toast('Doctor has been Pending successfully','success','top-right')->hideCloseButton();
        return back();
    }

    public function show(Doctor $doctor)
    {
        return view('admin.doctors.show', compact('doctor'));
    }

    public function destroy(Doctor $doctor)
    {
        $doctor->delete();
        toast('Doctor has been Deleted successfully','error','top-right')->hideCloseButton();
        return back();

    }
}

app/Http/Controllers/Api/DoctorController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\DoctorResource;
use App\Models\Doctor;
use App\Traits\ApiResponse;
use Illuminate\Http\Request;

class DoctorController extends Controller
{
    use ApiResponse;


    public function index()
    {
        $data = DoctorResource::collection(Doctor::paginate($this->paginate));

        return $this->apiResponse($data, null, 202);

    }

    public function show($id)
    {
        $doctor = Doctor::find($id);

        if ($doctor) {
            return $this->apiResponse(new DoctorResource($doctor));

        }

        return $this->apiResponse(null, 'No Doctor Found', 404);

    }
}

app/Http/Controllers/Doctor/DoctorAuth.php
<?php

namespace App\Http\Controllers\Doctor;

use App\Http\Controllers\Controller;
use App\Http\Requests\Doctor\Store;
use App\Models\Admin;
use App\Models\Doctor;
use App\Providers\RouteServiceProvider;
use Illuminate\Http\Request;

class DoctorAuth extends Controller
{


    public function register() {
        return view('doctor.register');
    }

    public function store(Store $request) {

        $data = $request->except(['password', 'password_confirmation']);
        $data['password'] = bcrypt($request->password);
        Doctor::create($data);
        return redirect(url('doctor/login'));
    }

    public function login() {
        return view('doctor.login');
    }

    public function dologin() {
        $rememberme = request('rememberme') === 1;

        if (auth()->guard('doctor')->attempt(['email' => request('email'), 'password' => request('password')], $rememberme)) {
            return redirect(RouteServiceProvider::DOCTOR_HOME);
        }

        session()->flash('error', 'These credentials do not match our records.');
        return back();
    }

    public function logout() {
        auth()->guard('doctor')->logout();
        return redirect(url('/'));
    }
}

app/Http/Controllers/Doctor/HomeController.php
<?php

namespace App\Http\Controllers\Doctor;

use App\Http\Controllers\Controller;
use App\Notifications\ReservationStatus;
use App\Models\Reservation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class HomeController extends Controller
{
    public function index()
    {
        $reservations = doctor()->reservations()->paginate(20);
        return view('doctor.home', compact('reservations') );
    }

    public function editReservation(Reservation $reservation)
    {
        if($reservation->doctor_id === doctor()->id) {
            return view('doctor.show-reservation', compact('reservation') );
        }

        return abort(404);
    }

    public function UpdateReservation(Reservation $reservation, Request $request)
    {
        $reservation->placement = $request->placement;
        $reservation->save();

        $reservation->user->notify(new ReservationStatus($reservation->status,$reservation->user->name));
        Mail::to($reservation->user->email)->send(new \App\Mail\ReservationStatus($reservation->user->name, $reservation->status, $reservation->created_at));

        return redirect(url('doctor/home'));
    }
}

resources/views/admin/doctors/index.blade.php
@extends('layouts.back-end.app', ['model' => 'Doctor'])

@section('content')

    <div class="card">

        <div class="card-header with-border">

            <form action="{{ aurl('doctor/index') }}" method="get">

                <div class="row">

                    <div class="col-md-4">
                        <input type="text" name="search" class="form-control" placeholder="search" value="{{ request()->search }}">
                    </div>

                    <div class="col-md-4">
                        <button type="submit" class="btn btn-info"><i class="fa fa-search"></i> Search</button>
                    </div>

                </div>
            </form><!-- end of form -->

        </div><!-- end of box header -->

        <div class="card-body">

            @if ($doctors->count() > 0)

                <table class="table table-hover">

                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Specialty</th>
                        <th>Fees</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($doctors as $index=>$doctor)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $doctor->name }}</td>
                            <td>{{ $doctor->specialty }}</td>
                            <td>{{ $doctor->fees }}</td>
                            <td><p class="btn btn-sm {{ $doctor->status === 'Pending' ? 'btn-warning' : 'btn-success' }} ">{{ $doctor->status }}</p></td>
                            <td>
                                <a href="{{ aurl('doctor/'. $doctor->id ) }}" class="btn btn-primary btn-sm"><i class="fa fa-eye"></i> Show</a>
                                <form action="{{ route('dashboard.doctor.destroy', $doctor->id) }}" method="post" style="display: inline-block">
                                    {{ csrf_field() }}
                                    {{ method_field('delete') }}
                                    <button type="submit" class="btn btn-danger delete btn-sm"><i class="fa fa-trash"></i> Delete</button>
                                </form><!-- end of form -->
                                <a href="{{ aurl('doctor/'. $doctor->id . '/edit') }}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i> {{ $doctor->status === 'Pending' ? 'Approved' : 'Pending' }} Doctor</a>

                            </td>
                        </tr>

                    @endforeach
                    </tbody>

                </table><!-- end of table -->

                {{ $doctors->appends(request()->query())->links() }}

            @else

                <h2>No Data Found</h2>

            @endif

        </div><!-- end of box body -->


    </div><!-- end of box -->

@endsection

resources/views/admin/doctors/show.blade.php
@extends('layouts.back-end.app', ['model' => 'Doctor'])

@section('content')

    <div class="card">

        <div class="card-body">

                <div class="row">
                    <div class="col-sm-2">Status : </div>
                    <div class="col-sm-10">
                        {{ $doctor->status }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">Name : </div>
                    <div class="col-sm-10">
                        {{ $doctor->name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">Specialty : </div>
                    <div class="col-sm-10">
                        {{ $doctor->specialty }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">Email : </div>
                    <div class="col-sm-10">
                        {{ $doctor->email }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">Fees : </div>
                    <div class="col-sm-10">
                        {{ $doctor->fees }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">Location : </div>
                    <div class="col-sm-10">
                        {{ $doctor->location }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">Description : </div>
                    <div class="col-sm-10">
                        {{ $doctor->description }}
                    </div>
                </div>

        </div><!-- end of box body -->
        <h2 class="text-center">Reservations</h2>
        <div class="card container">
            <table class="table table-hover">

                <thead>
                <tr>
                    <th>#</th>
                    <th>User</th>
                    <th>Status</th>
                    <th>Date</th>
                </tr>
                </thead>

                <tbody>
                @foreach ($doctor->reservations as $index=>$reservation)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $reservation->user->name }}</td>
                        <td>{{ $reservation->status }}</td>
                        <td>{{ $reservation->created_at->format('Y-M-D') }}</td>
                @endforeach
                </tbody>

            </table><!-- end of table -->
        </div>

    </div><!-- end of box -->

@endsection