routes/admin.php
<?php

use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Route;

Route::prefix('dashboard')->name('dashboard.')->group(function () {


    Route::get('/login', 'AdminAuth@login');
    Route::post('/login', 'AdminAuth@doLogin');
    Config::set('auth.defines', 'admin');

    Route::group(['middleware' => 'admin:admin'], function () {

        Route::get('/', 'HomeController@index');

        // admin routes
        Route::resource('admin', 'AdminController');

        // doctor routes
        Route::resource('doctor', 'DoctorController')->except(['create','store']);

        // user routes
        Route::resource('user', 'UserController')->except(['create','store']);

        // reservation routes
        Route::get('reservation', 'ReservationController@allReservation');
        Route::get('reservation/accepted', 'ReservationController@acceptedReservation');
        Route::get('reservation/rejected', 'ReservationController@rejectedReservation');
        Route::get('reservation/report', 'ReservationController@reportReservation');

        Route::post('/logout', 'AdminAuth@logout');

    });


});//end of dashboard routes

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Auth::routes();


Route::namespace('User')->group(function (){

    Route::get('/', 'WelcomeController@index')->name('home');

//    Route::get('/doctor/{doctor}', 'WelcomeController@showDoctor');

    Route::get('/reservation/{id}', 'ReservationController@store')->middleware('auth');


});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;


    protected $fillable = [
        'name', 'email', 'password', 'is_banned'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function getStatusAttribute()
    {
        if ($this->is_banned === 0) {
            return '';
        }

        return 'Banned';
    }


    public function reservations()
    {
        return $this->hasMany(Reservation::class);
    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $users = User::where(function ($q) use ($request) {

            return $q->when($request->search, function ($query) use ($request) {

                return $query->where('name', 'like', '%' . $request->search . '%')
                    ->orWhere('email', 'like', '%' . $request->search . '%');

            });

        })->latest()->paginate(5);

        return view('admin.users.index', compact('users'));
    }

    public function edit(User $user)
    {

        if ($user->is_banned === 0) {
            $user->is_banned = 1; // Ban User
            $user->save();
            toast('User has been banned successfully','success','top-right')->hideCloseButton();
            return back();
        }

        $user->is_banned = 0;  // unbanned user
        $user->save();
        toast('User has been unbanned successfully','success','top-right')->hideCloseButton();
        return back();
    }

    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));

    }
    public function destroy(User $user)
    {
        $user->delete();
        toast('User has been Deleted successfully','error','top-right')->hideCloseButton();
        return back();

    }
}

app/Http/Controllers/User/ReservationController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Doctor;
use Illuminate\Http\Request;

class ReservationController extends Controller
{
    public function store($id)
    {
        $doctor = Doctor::find($id);
        $doctor->reservations()->create([
                'user_id' => auth()->user()->id
        ]);

        return back();
    }
}

app/Http/Controllers/User/WelcomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Doctor;
use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index()
    {
        $doctors = Doctor::approved()->get();
        return view('welcome', compact('doctors'));
    }

    public function showDoctor(Doctor $doctor)
    {
        return view('user.doctor', compact('doctor'));
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.back-end.app', ['model' => 'User'])

@section('content')

    <div class="card">

        <div class="card-header with-border">

            <form action="{{ aurl('user/index') }}" method="get">

                <div class="row">

                    <div class="col-md-4">
                        <input type="text" name="search" class="form-control" placeholder="search" value="{{ request()->search }}">
                    </div>

                    <div class="col-md-4">
                        <button type="submit" class="btn btn-info"><i class="fa fa-search"></i> Search</button>
                    </div>

                </div>
            </form><!-- end of form -->

        </div><!-- end of box header -->

        <div class="card-body">

            @if ($users->count() > 0)

                <table class="table table-hover">

                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($users as $index=>$user)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td><p class="btn btn-sm {{ $user->status === 'Banned' ? 'btn-danger' : '' }} ">{{ $user->status }}</p></td>
                            <td>
                                <a href="{{ aurl('user/'. $user->id ) }}" class="btn btn-primary btn-sm"><i class="fa fa-eye"></i> Show</a>
                                <form action="{{ route('dashboard.user.destroy', $user->id) }}" method="post" style="display: inline-block">
                                    {{ csrf_field() }}
                                    {{ method_field('delete') }}
                                    <button type="submit" class="btn btn-danger delete btn-sm"><i class="fa fa-trash"></i> Delete</button>
                                </form><!-- end of form -->
                                <a href="{{ aurl('user/'. $user->id . '/edit') }}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i> {{ $user->status === 'Banned' ? 'Unbanned' : 'Ban' }} User</a>

                            </td>
                        </tr>

                    @endforeach
                    </tbody>

                </table><!-- end of table -->

                {{ $users->appends(request()->query())->links() }}

            @else

                <h2>No Data Found</h2>

            @endif

        </div><!-- end of box body -->


    </div><!-- end of box -->

@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.back-end.app', ['model' => 'User'])

@section('content')

    <div class="card">

        <div class="card-body">

            <div class="row">
                <div class="col-sm-2">Name : </div>
                <div class="col-sm-10">
                    {{ $user->name }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">Email : </div>
                <div class="col-sm-10">
                    {{ $user->email }}
                </div>
            </div>


        </div><!-- end of box body -->
        <h2 class="text-center">Reservations</h2>
        <div class="card container">
            <table class="table table-hover">

                <thead>
                <tr>
                    <th>#</th>
                    <th>Doctor</th>
                    <th>Status</th>
                    <th>Date</th>
                </tr>
                </thead>

                <tbody>
                @foreach ($user->reservations as $index=>$reservation)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $reservation->doctor->name }}</td>
                        <td>{{ $reservation->status }}</td>
                        <td>{{ $reservation->created_at->format('Y-M-D') }}</td>
                @endforeach
                </tbody>

            </table><!-- end of table -->
        </div>

    </div><!-- end of box -->

@endsection