routes/admin.php
<?php

use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Route;

Route::prefix('dashboard')->name('dashboard.')->group(function () {


    Route::get('/login', 'AdminAuth@login');
    Route::post('/login', 'AdminAuth@doLogin');
    Config::set('auth.defines', 'admin');

    Route::group(['middleware' => 'admin:admin'], function () {

        Route::get('/', 'HomeController@index');

        // admin routes
        Route::resource('admin', 'AdminController');

        // doctor routes
        Route::resource('doctor', 'DoctorController')->except(['create','store']);

        // user routes
        Route::resource('user', 'UserController')->except(['create','store']);

        // reservation routes
        Route::get('reservation', 'ReservationController@allReservation');
        Route::get('reservation/accepted', 'ReservationController@acceptedReservation');
        Route::get('reservation/rejected', 'ReservationController@rejectedReservation');
        Route::get('reservation/report', 'ReservationController@reportReservation');

        Route::post('/logout', 'AdminAuth@logout');

    });


});//end of dashboard routes

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Auth::routes();


Route::namespace('User')->group(function (){

    Route::get('/', 'WelcomeController@index')->name('home');

//    Route::get('/doctor/{doctor}', 'WelcomeController@showDoctor');

    Route::get('/reservation/{id}', 'ReservationController@store')->middleware('auth');


});

resources/views/admin/admins/create.blade.php
@extends('layouts.back-end.app', ['model' => 'Admin'])

@section('content')

    @component('admin._form', ['method' => 'POST', 'url' => aurl('admin') , 'submit' => 'Create'])

        @slot('input')

            <div class="form-group">
                <label>Name</label>
                {!! Form::text('name',old('name'), ['class'=> 'form-control']) !!}
            </div>

            <div class="form-group">
                <label>Email</label>
                {!! Form::text('email',old('email'), ['class'=> 'form-control']) !!}
            </div>

            <div class="form-group">
                <label>Password</label>
                {!! Form::password('password', ['class'=> 'form-control']) !!}
            </div>

            <div class="form-group">
                <label>Password Confirmation</label>
                {!! Form::password('password_confirmation', ['class'=> 'form-control']) !!}
            </div>

        @endslot

    @endcomponent

@endsection

resources/views/admin/admins/edit.blade.php
@extends('layouts.back-end.app', ['model' => 'Admin'])

@section('content')

    @component('admin._form', ['method' => 'PUT', 'url' => aurl('admin/' . $admin->id)  , 'submit' => 'Edit'])

        @slot('input')
            <div class="form-group">
                {!! Form::label('Name') !!}
                {!! Form::text('name',$admin->name, ['class'=> 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('Email') !!}
                {!! Form::email('email',$admin->email, ['class'=> 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('Password') !!}
                {!! Form::password('password', ['class'=> 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('Password Confirmation') !!}
                {!! Form::password('password_confirmation', ['class'=> 'form-control']) !!}
            </div>

        @endslot

    @endcomponent

@endsection

resources/views/admin/admins/index.blade.php
@extends('layouts.back-end.app', ['model' => 'Admin'])

@section('content')

    <div class="card">

        <div class="card-header with-border">

            <form action="{{ aurl('admin/index') }}" method="get">

                <div class="row">

                    <div class="col-md-4">
                        <input type="text" name="search" class="form-control" placeholder="search" value="{{ request()->search }}">
                    </div>

                    <div class="col-md-4">
                        <button type="submit" class="btn btn-info"><i class="fa fa-search"></i> Search</button>
                        <a href="{{ aurl('admin/create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Create </a>

                    </div>

                </div>
            </form><!-- end of form -->

        </div><!-- end of box header -->

        <div class="card-body">

            @if ($admins->count() > 0)

                <table class="table table-hover">

                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($admins as $index=>$admin)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $admin->name }}</td>
                            <td>{{ $admin->email }}</td>
                            <td>
                                <a href="{{ aurl('admin/'. $admin->id . '/edit') }}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                <form action="{{ route('dashboard.admin.destroy', $admin->id) }}" method="post" style="display: inline-block">
                                    {{ csrf_field() }}
                                    {{ method_field('delete') }}
                                    <button type="submit" class="btn btn-danger delete btn-sm"><i class="fa fa-trash"></i> Delete</button>
                                </form><!-- end of form -->
                            </td>
                        </tr>

                    @endforeach
                    </tbody>

                </table><!-- end of table -->

                {{ $admins->appends(request()->query())->links() }}

            @else

                <h2>No Data Found</h2>

            @endif

        </div><!-- end of box body -->


    </div><!-- end of box -->

@endsection